version: '3.8'

services:
  users-service:
    build: ./users-service
    ports:
      - "8081:8081"
    networks:
      - app-network

  tasks-service:
    build: ./tasks-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network: